### ISSUE TITLE
plugin is not functioning

### ISSUE THREAD

**Issue by newMember** [BenGriffiths/jquery-save-as-you-type#1]
Hi,

I am new to Jquery. In my project, we have save-as-you-type autosave requirement. I tried using this plugin, but I was unable to make it work.

I am following these steps. Correct me if I am doing wrong anywhere.
1. I have created sample html with one input field.
2. In this html, I am using this function. 

<script type="text/javascript">
    $(function(){
    alert("hello");
    $("#growth").sayt();
    });
</script>

I have put some alert messages inside plugin. So plugin was detected but  was not able to autosave data into cookies.
I guess this piece code is not getting executed

this.contents().find('input').each(function(index)

Any help would be highly appreciated.  

Thanks,
Ranjan.

**Comment by libishi** [comment]
hello ben, 
I stil get this error "TypeError: $(...).sayt is not a function"
please help :D
